name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test


    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the provided token
        publish_dir: .  # Adjust this if your build output is in a specific directory
        publish_branch: gh-pages  # Specify the branch to deploy to

env:
  MY_ENV_VAR: ${{ secrets.MY_ENV_VAR }}  # Example for using secretss
